[package]
name = "yew-app"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
web-sys = "0.3"
wasm-bindgen = "0.2"
gloo-net = "0.3"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen-futures = "0.4"
gloo-console = "0.2"
serde_json = "1.0"
